name: hostelapplication
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:

  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  uuid: ^3.0.6
  provider: ^6.0.3
  rflutter_alert:
  date_time_picker:
  image_picker: ^0.8.5+3
  file_picker:
  # image_downloader: ^0.31.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^14.0.0+2
  http: ^1.0.0
  file: ^6.1.4


dev_dependencies:

  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.1.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
  
  # fonts:
  #   -family: Kanit
  #     fonts:
  #       -asset: assets/fonts/Kanit-Bold.ttf
  #       # - asset: assets/fonts/Kanit-Italic.ttf
  #         style: Bold
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

